#!/bin/bash

VENV_ROOT="/usr/share/examshell/venv"

source $VENV_ROOT/bin/activate

python3.8 /usr/share/examshell/venv/lib/python3.8/site-packages/examshell-3.0-py3.8.egg/EGG-INFO/scripts/examshell-cli.py

deactivate
